# Configuration for PicoChat
URL = "http://localhost:11434/api/chat"
# Model = "Qwen3-8B-8bit"
Model = "DeepSeek-R1-Distill-Qwen-14B-6bit"
Context = 50
Prompt = """
You are Large Language Model. Answer as concisely as possible. Your answers should be informative, helpful and engaging.
"""
